version: '3'
services:
  app:
    build: .
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # make this bind mnt to client
    container_name: portfolio-temp
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    command: npm start