# dev env dockerfile
FROM node:18.11.0
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --force && npm cache clean --force
COPY . .
# --host so vite is reachable from outside the container
CMD ["npm", "run", "start", "--", "--host"]
EXPOSE 5173
