version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - ./src:/usr/src/app/src
#      - ./node_modules:/usr/src/app/node_modules:cached
    container_name: portfolio-dev
    restart: always
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true # outdated watch method
    ports:
      - 3000:3000
    command: npm start