FROM node:18.11.0 as build
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
# vite outputs to dist/, not build/
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
EXPOSE 8080:80